# Site settings
title: villetormala.com
email: ville.tormala@iki.fi
description: > # Writings about software development.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
enable_retina: true
permalink: :title
nav_list:
  Home : ['Home', '/', 'fa-home']
  Archive : ['All posts', '/archive', 'fa-archive']
  About : ['About', '/about', 'fa-anchor']
# Home_Alt : ['Home Alt', '/home-alt', 'fa-home']
# Home_Alt_2 : ['Home Alt 2', '/home-alt-2/', 'fa-home']
single_footer: '<p>Thank you for reading. You are awesome!</p>'
footer_links:
    About: ['About', '/about']
    Archive: ['Archive', '/archive']


# Build settings
# markdown: kramdown
